name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm install -g vercel@41.5.0  # Specify the version if needed

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: vercel --prod --yes --token $VERCEL_TOKEN